### ISSUE TITLE
use with NAV2 SLAM

### ISSUE THREAD

**Issue by robvoi** [DaniGarciaLopez/ros2_explorer#2]
I am using NAV2 SLAM and Navigation on a real robot.
Is there a way to hook in the explorer into the nav2 map/slam stack?

**Comment by DaniGarciaLopez** [comment]
Hi @robvoi. Sorry for the late reply.

I guess by "nav2 slam" you mean "slam_toolbox", right? I haven't tried it but it should work, just replace cartographer with the slam package you prefer.
