### ISSUE TITLE
Discoverer Exploration algorithm doesn't work

### ISSUE THREAD

**Issue by 4ku** [DaniGarciaLopez/ros2_explorer#4]
After launching gazebo (`ros2 launch explorer_bringup map10.launch.py`) I've tried to use Discoverer Exploration algorithm, but it's stuck:
![image](https://user-images.githubusercontent.com/23717347/193884088-ea8bbdf4-1066-4f4b-a406-e4ba43f757a1.png)

However Wanderer Exploration works well.

**Comment by DaniGarciaLopez** [comment]
Hi @4ku, sorry for the late reply. 

Wanderer and Discoverer algorithms are implemented as action servers. By the screen capture I assume the excecutable `discoverer_server` from the package `explorer_wanderer` was not launched correctly. 

Check if you get any error after launching `ros2 launch explorer_bringup map10.launch.py` and the node `discoverer_server` is running.
