### ISSUE TITLE
Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist

### ISSUE THREAD

**Issue by cataclism** [DaniGarciaLopez/ros2_explorer#6]
I have a problem when I launch the map.
I get this error:

[rviz2-7] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist

[rviz2-7] at line 156 in /tmp/binarydeb/ros-galactic-tf2-0.17.4/src/buffer_core.cpp

What happens is that the robot goes straight and then it crashes on the wall as it was not "sensing it"

I've downloaded the package as said. I'm using ROS2 Galactic

**Comment by DaniGarciaLopez** [comment]
If the frame "map" is not being published most likely there is a problem with cartographer. Check if you didn't receive any other warnings or errors and all nodes are running. I've not personally tried this repo in galactic, but it should work fine as we didn't detected any major incompatibilities in humble.
